# Final Project
## By: Kevin Chen

#Download data:
```{r,eval=FALSE}
temp = tempfile(fileext = ".xls") 
dataURL <- "https://github.com/chjy0205/data/blob/master/Community%20Reporting%20Areas.xls?raw=true" 
download.file(dataURL, destfile=temp, mode='wb') 
```
#Select data
```{r,eval=FALSE}
AreaAcre=read_excel(temp,1,na='.')[,c(1:7,8)]
AreaAcre=as.data.frame(AreaAcre)
names(AreaAcre)
```

```{r,eval=FALSE}
AreaAcreCommunity=AreaAcre
head(AreaAcreCommunity)
str(AreaAcreCommunity)
summary(AreaAcreCommunity$`Area Acres`)
```
#Get Dispersion
```{r,eval=FALSE}
library(moments)
sd(AreaAcreCommunity$`Area Acres`,na.rm = T)
sd(AreaAcreCommunity$`Area Acres`,na.rm = T)/mean(AreaAcreCommunity$`Area Acres`,na.rm = T)
```
#Skewness
```{r,eval=FALSE}
skewness(AreaAcreCommunity$`Area Acres`,na.rm = T)
```
#Kurtosis
```{r,eval=FALSE}
kurtosis(AreaAcreCommunity$`Area Acres`,na.rm = T)
```
#Plot
```{r,eval=FALSE}
data=AreaAcreCommunity[is.finite(AreaAcreCommunity$`Area Acres`),]
var=data$`Area Acres`
mnVar=mean(var, na.rm=T)
sdVar=sd(var, na.rm=T)
library(ggplot2)
base=ggplot(data, aes(x=var))
hist= base+geom_histogram(fill="green",color="grey",aes(y=..density..))
histAndNormal = hist + stat_function(fun=dnorm,
                                     color="red",
                                     args=list(mean=mnVar,sd=sdVar))
histAndNormal = hist + stat_function(fun=dnorm,
                                     color="red",
                                     args=list(mean=mnVar,sd=sdVar))
histAndNormal
```
#Second variable
```{r,eval=FALSE}
Population=read_excel(temp,1,na='.')[,c(1:7,10)]
Population=as.data.frame(Population)
names(Population)
```

```{r,eval=FALSE}
PopulationCommunity=Population
head(PopulationCommunity)
str(PopulationCommunity)
summary(PopulationCommunity$`Total population`)
```

```{r,eval=FALSE}
library(moments)
sd(PopulationCommunity$`Total population`,na.rm = T)
sd(PopulationCommunity$`Total population`,na.rm = T)/mean(PopulationCommunity$`Total population`,na.rm = T)
skewness(PopulationCommunity$`Total population`,na.rm = T)
```

```{r,eval=FALSE}
kurtosis(PopulationCommunity$`Total population`,na.rm = T)
```

```{r,eval=FALSE}
data=PopulationCommunity[is.finite(PopulationCommunity$`Total population`),]
var=data$`Total population`
mnVar=mean(var, na.rm=T)
sdVar=sd(var, na.rm=T)
library(ggplot2)
base=ggplot(data, aes(x=var))
hist= base+geom_histogram(fill="green",color="grey",aes(y=..density..))
histAndNormal = hist + stat_function(fun=dnorm,
                                     color="red",
                                     args=list(mean=mnVar,sd=sdVar))
histAndNormal = hist + stat_function(fun=dnorm,
                                     color="red",
                                     args=list(mean=mnVar,sd=sdVar))
histAndNormal
```
```